#pragma once

//用于分辨不同Toon Shading Model
#define TOONMODEL_DEFAULT				0
#define TOONMODEL_FACE					1
#define TOONMODEL_HAIR					2
#define TOONMODEL_EYE					3
#define TOONMODEL_SKIN					4
// SCF表示ShadowCastFlag
#define SCF_DEFAULT						0x00
#define SCF_DISABLEONSELF				0x01
#define SCF_DISABLEONFACE				0x02
#define SCF_DISABLEONEYE				0x04
#define SCF_DISABLEONTOON				0x08
#define SCF_DISABLEALLTOON				0x10

struct FToonBuffer
{
	// -----------------------------------ToonBufferA-------------------------------
	uint SelfID;				// ToonBufferA.r (8)
	uint ObjectID;				// ToonBufferA.g (8)
	uint ToonModel;				// ToonBufferA.b (3)
	uint ShadowCastFlag;		// ToonBufferA.b (5)

	float HairShadowOffset;		// ToonBufferA.a (8)

	float4 ToonBufferB;
	float4 ToonBufferC;
};

// Encode / Decode Helper
// float all in 0 ~ 1
uint GetBitsMaxValue(int Bits = 8) {return (1L << Bits) - 1;}

float EncodeUintToFloat(uint Src, int BitSrc = 8)
{
	return float(Src) / float(GetBitsMaxValue(BitSrc));
}

float4 EncodeUintToFloat(uint4 Src, int BitSrc = 8)
{
	return float4(Src) / float(GetBitsMaxValue(BitSrc));
}

uint EncodeUint2ToUint(uint Src1, uint Src2, int BitsSrc1 = 8, int BitsSrc2 = 8)
{
	return ((Src1 & GetBitsMaxValue(BitsSrc1)) << BitsSrc2) |
	(Src2 & GetBitsMaxValue(BitsSrc2));
}

void DecodeUint2FromUint(uint Src, out uint Dst1, out uint Dst2, int BitsDst1 = 8, int BitsDst2 = 8)
{
	Dst1 = (Src >> BitsDst2)    & GetBitsMaxValue(BitsDst1);
	Dst2 = Src					& GetBitsMaxValue(BitsDst2);
}

uint EncodeFloatToUint(float Src1, int BitsSrc1 = 8)
{
	return saturate(Src1) * GetBitsMaxValue(BitsSrc1);
}

uint4 EncodeFloatToUint(float4 Src1, int BitsSrc1 = 8)
{
	return saturate(Src1) * GetBitsMaxValue(BitsSrc1);
}

void EncodeToonBuffer(FToonBuffer ToonBuffer, in out uint4 ToonBufferA, in out uint4 ToonBufferB, in out uint4 ToonBufferC)
{
	ToonBufferA.r = ToonBuffer.SelfID & GetBitsMaxValue(8);
	ToonBufferA.g = ToonBuffer.ObjectID & GetBitsMaxValue(8);
	ToonBufferA.b = EncodeUint2ToUint(ToonBuffer.ToonModel, ToonBuffer.ShadowCastFlag, 3, 5);
	ToonBufferA.a = EncodeFloatToUint(ToonBuffer.HairShadowOffset);

	ToonBufferB = EncodeUintToFloat(ToonBufferB);
	ToonBufferC = EncodeUintToFloat(ToonBufferC);
}

// 解码ToonBuffer
FToonBuffer DecodeToonDataFromBuffer(uint4 ToonBufferA, uint4 ToonBufferB, uint4 ToonBufferC, float4 CustomData)
{
	
	FToonBuffer ToonBuffer;
	
	ToonBuffer.SelfID = ToonBufferA.r;
	ToonBuffer.ObjectID = ToonBufferA.g;
	ToonBuffer.ShadowCastFlag = (ToonBufferA.b >> 0) & GetBitsMaxValue(5);
	ToonBuffer.ToonModel = (ToonBufferA.b >> 5) & GetBitsMaxValue(3);
	ToonBuffer.HairShadowOffset = EncodeUintToFloat(ToonBufferA.a);
	
	return ToonBuffer;
}


// Toon自定义Payload
struct FToonPayloadData
{
	uint ToonData;					

	// 按位编码ToonPayload
	uint GetSelfID()							{return (ToonData >> 0) & GetBitsMaxValue(8);}
	void SetSelfID(uint ID)						{ToonData |= ((ID & GetBitsMaxValue(8)) << 0);}

	uint GetObjectID()							{return (ToonData >> 8) & GetBitsMaxValue(8);}
	void SetObjectID(uint ID)					{ToonData |= ((ID & GetBitsMaxValue(8)) << 8);}
	
	uint GetShadowCastFlag()					{return (ToonData >> 16) & GetBitsMaxValue(5);}
	void SetShadowCastFlag(uint Flag)			{ToonData |= ((Flag & GetBitsMaxValue(5)) << 16);}
	
	uint GetToonModel()							{return (ToonData >> 21) & GetBitsMaxValue(3);}
	void SetToonModel(uint ToonModel)			{ToonData |= ((ToonModel & GetBitsMaxValue(3)) << 21);}
	
};

FToonPayloadData GetToonPayloadByToonBuffer(FToonBuffer ToonBuffer)
{
	FToonPayloadData ToonPayloadData = (FToonPayloadData)0;
	ToonPayloadData.SetSelfID(ToonBuffer.SelfID);
	ToonPayloadData.SetObjectID(ToonBuffer.ObjectID);
	ToonPayloadData.SetToonModel(ToonBuffer.ToonModel);
	ToonPayloadData.SetShadowCastFlag(ToonBuffer.ShadowCastFlag);

	return ToonPayloadData;
}
// Toon Shadow Buffer
float4 EncodeToonShadow(float SurfaceShadow, float TransmissionShadow, float HairShadow)
{
	float4 ToonShadow = 1.0f;
	ToonShadow.r = SurfaceShadow;
	ToonShadow.g = TransmissionShadow;
	ToonShadow.b = HairShadow;
	return ToonShadow;
}