#include "../Common.ush"
#include "/Engine/Generated/Material.ush"
#include "/Engine/Generated/VertexFactory.ush"

struct FSimpleMeshPassVSToPS
{
	FVertexFactoryInterpolantsVSToPS FactoryInterpolants;
	float4 Position : SV_POSITION;
};

void MainVS(
	FVertexFactoryInput Input,
	out FSimpleMeshPassVSToPS Output)
{

	float4 ClipSpacePosition;
	
	ResolvedView = ResolveView();

	FVertexFactoryIntermediates VFIntermediates = GetVertexFactoryIntermediates(Input);

	float4 WorldPos = VertexFactoryGetWorldPosition(Input, VFIntermediates);
	float3 WorldNormal = VertexFactoryGetWorldNormal(Input, VFIntermediates);

	float3x3 TangentToLocal = VertexFactoryGetTangentToLocal(Input, VFIntermediates);

	FMaterialVertexParameters VertexParameters = GetMaterialVertexParameters(Input, VFIntermediates, WorldPos.xyz, TangentToLocal);
	WorldPos.xyz += GetMaterialWorldPositionOffset(VertexParameters);

	float4 RasterizedWorldPosition = VertexFactoryGetRasterizedWorldPosition(Input, VFIntermediates, WorldPos);
	ClipSpacePosition = mul(RasterizedWorldPosition, ResolvedView.TranslatedWorldToClip);
	Output.Position = INVARIANT(ClipSpacePosition);
	Output.FactoryInterpolants = VertexFactoryGetInterpolantsVSToPS(Input, VFIntermediates, VertexParameters);
}

void MainPS(
	FSimpleMeshPassVSToPS Input,
	out uint4 OutColor1 : SV_Target0,
	out uint4 OutColor2 : SV_Target1,
	out uint4 OutColor3 : SV_Target2)
{
	// 获取像素的材质参数(此处的材质就是材质辑器编辑出来的材质).
	FMaterialPixelParameters MaterialParameters = GetMaterialPixelParameters(Input.FactoryInterpolants, Input.Position);
	// FPixelMaterialInputs用于获取材质编辑器的针脚
	// FPixelMaterialInputs PixelMaterialInputs;
	uint4 Color1 = 0;
	uint4 Color2 = 0;
	uint4 Color3 = 0;
#ifdef  HAVE_GetToonMaterialOutput0
	Color1.rgb = GetToonMaterialOutput0(MaterialParameters);
#endif
#ifdef  HAVE_GetToonMaterialOutput1
	Color2.rgb = GetToonMaterialOutput1(MaterialParameters);
#endif
#ifdef  HAVE_GetToonMaterialOutput2
	Color3.rgb = GetToonMaterialOutput2(MaterialParameters);
#endif

	OutColor1 = Color1;
	OutColor2 = Color2;
	OutColor3 = Color3;

}