#pragma once
#include "../DeferredShadingCommon.ush"

float Sigmoid(float x) {
	return 1.0f / (1.0f + exp(-x));
}
float2 TranslatedPositionToScreenUV(float3 TranslatedWorldPosition)
{
	float4 ViewPosition = mul(float4(TranslatedWorldPosition, 1.0), View.TranslatedWorldToView);
	float2 ScreenUV = float2(ViewPosition.xy /  (ViewPosition.z * GetTanHalfFieldOfView().xy));
	ScreenUV = ScreenUV * float2(0.5, -0.5) + float2(0.5, 0.5);
	return saturate(ScreenUV);
}

float BoxSDF(float3 Position, float3 BoxExtent)
{
	float3 q = abs(Position) - BoxExtent;
	return length(max(q, 0.0f)) + min(max(q.x, max(q.y, q.z)), 0.0f);
}

float2 TranslatedPositionToBufferUV(float3 TranslatedWorldPosition)
{
	float2 ScreenUV = TranslatedPositionToScreenUV(TranslatedWorldPosition);
	float2 BufferUV = (ScreenUV * View.ViewSizeAndInvSize.xy + View.ViewRectMin.xy) * View.BufferSizeAndInvSize.zw;
	return BufferUV;
}

// ToonFunctions:
float ToonShadowMask(float Lambert, float AttenuationSpeed, float ShadowOffset = 0.5)
{
	return smoothstep(ShadowOffset - AttenuationSpeed, ShadowOffset + AttenuationSpeed, Lambert);
}

float CelShadowMask(float Lambert, float AttenuationSpeed)
{
	AttenuationSpeed *= 0.1f;
	return smoothstep(0.5f - AttenuationSpeed, 0.5f + AttenuationSpeed, Lambert);
}

float GetToonSurfaceShadow(float Shadow, float ShadowAttenuationSpeed)
{
	return CelShadowMask(Shadow, ShadowAttenuationSpeed);
}
//皮肤shadow处理
float3 LerpMultiFloat3(float3 Var1, float3 Var2, float3 Var3, float3 Var4, float S)
{
	S *= 3;
	float3 Res;
	Res = lerp(Var1, Var2, saturate(S));
	S--;
	Res = lerp(Res, Var3, saturate(S));
	S--;
	Res = lerp(Res, Var4, saturate(S));
	return Res;
}

float3 GetSkinShadow(float Shadow, float3 Color0)
{
	float3 Color1 = Color0 * float3(0.5,0,0);
	float3 Color2 = Color0 * float3(1.0, 0.5, 0);
	return LerpMultiFloat3(0, Color1, Color2, 1, Shadow);
}

half ToonStep(float halfLambert, float smoothness = 0.001f, float threshold = 0.5f)
{
	smoothness = max(smoothness, 0.001f);
	return smoothstep(threshold - smoothness, threshold + smoothness, halfLambert);
}

float LinearStep(float MinValue, float MaxValue, float Value)
{
	return max(0, min(1, (Value - MinValue) / (MaxValue - MinValue)));
}

bool IsToonMainLight()
{
#if IS_TOON_MAINLIGHT
	return true;
#else
	return false;
#endif
}

float ToonFresnel(float3 N, float3 V, float Exponent, float BaseReflectionFraction = 0.0f)
{
	half NoV = max(0.0f, dot(N, V));
	half Fresnel = pow(abs(1 - max(NoV, 0.0f)), Exponent);
	Fresnel = Fresnel * (1 - BaseReflectionFraction) + BaseReflectionFraction;
	return Fresnel;
}

float StrandSpecular(float3 T, float3 L, float3 V, half Exponent, half Scale = 1.0f )
{
	float3 H = normalize(V + L);
	float ToH = dot(T, H);
	float sinTH = sqrt(1.0 - ToH * ToH);

	float dirAttenuation = smoothstep(-1.0, 0.0, ToH);
	return dirAttenuation * pow(sinTH, Exponent) * Scale;
}

float3 ShiftTangent(float3 T, float3 N, half shift)
{
	return normalize(T + shift* N);
}

float GetHairShadow(FGBufferData GBuffer, FDeferredLightData LightData, float2 ScreenUV)
{
	float Shadow = 1.0f;
	
	float k = 100.0f;
	// 屏幕空间LightDirection
	// View.TranslatedWorldToCameraView用于将世界空间变换到屏幕空间
	float3 LightDirVS = mul(LightData.Direction, (float3x3)(View.TranslatedWorldToCameraView));
	// 翻转LightDirVS的y方向，不然Offset上下会反，可能会出现OpenGL和DirectX不一致的情况，不过到时候遇到再改
	LightDirVS.y = -LightDirVS.y;
	// 修正摄像机距离对偏移距离的影响
	LightDirVS *= (100.0f / CalcSceneDepth(ScreenUV));

	// View.BufferSizeAndInvSize.xy是屏幕分辨率；View.BufferSizeAndInvSize.xy是屏幕分辨率的倒数
	float2 Offset = LightDirVS.xy * k * GBuffer.ToonBuffer.HairShadowOffset * View.BufferSizeAndInvSize.zw;
	float2 OffsetedUV = saturate(ScreenUV + Offset);
	
	FGBufferData OffsetedGBuffer = GetGBufferData(OffsetedUV);

	// 向光源反向偏移一段距离，如果此处是头发，那么原Texel在阴影下
	if (OffsetedGBuffer.ToonBuffer.ToonModel == TOONMODEL_HAIR
		&& OffsetedGBuffer.Depth < GBuffer.Depth
		&& OffsetedGBuffer.ToonBuffer.ObjectID == GBuffer.ToonBuffer.ObjectID)
	{
		Shadow = 0.0f;
	}
	
	return Shadow;
};
