#pragma once

#include "../Common.ush"
#include "ToonBufferCommon.ush"

FToonBuffer GetToonBuffer(FMaterialPixelParameters MaterialParameters)
{
	FToonBuffer ToonBuffer;
	ToonBuffer.SelfID = 0;
	ToonBuffer.ObjectID = 0;
	ToonBuffer.ToonModel = 0;
	ToonBuffer.ShadowCastFlag = 0;
	ToonBuffer.HairShadowOffset = 0.0f;
	ToonBuffer.SpecularSmoothness = 0.5f;
	ToonBuffer.SpecularOffset = 0.0f;
	ToonBuffer.ToonBufferC = 0.0f;
#if	NUM_MATERIAL_OUTPUTS_GETTOONBUFFEROUTPUT
	ToonBuffer.SelfID = clamp(GetToonBufferOutput0(MaterialParameters), 0.0f, 255.0f);

	ToonBuffer.ObjectID = clamp(GetToonBufferOutput1(MaterialParameters), 0.0f, 255.0f);

	ToonBuffer.ToonModel = clamp(GetToonBufferOutput2(MaterialParameters), 0.0f, 7.0f);

	ToonBuffer.ShadowCastFlag = clamp(GetToonBufferOutput3(MaterialParameters), 0.0f, 32.0f);

	ToonBuffer.HairShadowOffset = GetToonBufferOutput4(MaterialParameters);
	ToonBuffer.SpecularSmoothness = GetToonBufferOutput5(MaterialParameters);
	ToonBuffer.SpecularOffset = GetToonBufferOutput6(MaterialParameters);
	ToonBuffer.ToonBufferC = GetToonBufferOutput7(MaterialParameters);
#endif

	return ToonBuffer;
}

// Toon RayTracing Shadow
FToonPayloadData GetToonPayloadData(FMaterialPixelParameters MaterialParameters)
{
	FToonBuffer ToonBuffer = GetToonBuffer(MaterialParameters);
	
	return GetToonPayloadByToonBuffer(ToonBuffer);
}

// Toon Light Output
float3 GetToonLight(FMaterialPixelParameters MaterialParameters)
{
	float3 ToonLight = 0;
#if NUM_MATERIAL_OUTPUTS_GETTOONLIGHTOUTPUT > 0
	ToonLight = GetToonLightOutput0(MaterialParameters);
#endif
	return ToonLight;
}
