#pragma once
//用于分辨不同Toon Shading Model
#define TOONMODEL_DEFAULT				0
#define TOONMODEL_FACE					1
#define TOONMODEL_HAIR					2
#define TOONMODEL_EYE					3
#define TOONMODEL_SKIN					4
// SCF表示ShadowCastFlag
#define SCF_DEFAULT						0x00
#define SCF_DISABLEONSELF				0x01
#define SCF_DISABLEONFACE				0x02
#define SCF_DISABLEONEYE				0x04
#define SCF_DISABLEONTOON				0x08
#define SCF_DISABLEALLTOON				0x10

struct FToonBuffer
{
	// -----------------------------------ToonBufferA-------------------------------
	uint SelfID; // ToonBufferA.r (8)
	uint ObjectID; // ToonBufferA.g (8)
	uint ToonModel; // ToonBufferA.b (3)
	uint ShadowCastFlag; // ToonBufferA.b (5)
	
};
// Encode / Decode Helper
// float all in 0 ~ 1
uint GetBitsMaxValue(int Bits = 8) {return (1L << Bits) - 1;}
// Toon自定义Payload
struct FToonPayloadData
{
	uint ToonData;					

	// 按位编码ToonPayload
	uint GetSelfID()							{return (ToonData >> 0) & GetBitsMaxValue(8);}
	void SetSelfID(uint ID)						{ToonData |= ((ID & GetBitsMaxValue(8)) << 0);}

	uint GetObjectID()							{return (ToonData >> 8) & GetBitsMaxValue(8);}
	void SetObjectID(uint ID)					{ToonData |= ((ID & GetBitsMaxValue(8)) << 8);}
	
	uint GetShadowCastFlag()					{return (ToonData >> 16) & GetBitsMaxValue(5);}
	void SetShadowCastFlag(uint Flag)			{ToonData |= ((Flag & GetBitsMaxValue(5)) << 16);}

	uint GetToonModel()							{return (ToonData >> 21) & GetBitsMaxValue(3);}
	void SetToonModel(uint ToonModel)			{ToonData |= ((ToonModel & GetBitsMaxValue(3)) << 21);}
	
};

FToonPayloadData GetToonPayloadDataFromBuffer(float4 ToonBufferA)
{
	FToonPayloadData Out = (FToonPayloadData)0;
	uint4 ToonBufferABit = ToonBufferA;
	Out.SetSelfID(ToonBufferABit.r);
	Out.SetObjectID(ToonBufferABit.g);
	Out.SetShadowCastFlag((ToonBufferABit.b >> 0) & GetBitsMaxValue(5));
	Out.SetToonModel((ToonBufferABit.b >> 5) & GetBitsMaxValue(3));
	return Out;
}

float EncodeUintToFloat(uint Src, int BitSrc = 8)
{
	return float(Src) / float(GetBitsMaxValue(BitSrc));
}

uint EncodeFloatToUint(float Src1, int BitsSrc1 = 8)
{
	return saturate(Src1) * GetBitsMaxValue(BitsSrc1);
}

uint4 EncodeFloatToUint(float4 Src1, int BitsSrc1 = 8)
{
	return saturate(Src1) * GetBitsMaxValue(BitsSrc1);
}

// 解码ToonBuffer
FToonBuffer DecodeToonDataFromBuffer(uint4 ToonBufferA, uint4 ToonBufferB, uint4 ToonBufferC, float4 CustomData)
{
	
	FToonBuffer ToonBuffer;
	
	//uint4 ToonBufferABit = EncodeFloatToUint(ToonBufferA);
	uint4 ToonBufferABit = ToonBufferA;
	ToonBuffer.SelfID = ToonBufferABit.r;
	ToonBuffer.ObjectID = ToonBufferABit.g;
	ToonBuffer.ShadowCastFlag = (ToonBufferABit.b >> 0) & GetBitsMaxValue(5);
	ToonBuffer.ToonModel = (ToonBufferABit.b >> 5) & GetBitsMaxValue(3);
	
	return ToonBuffer;
}

// ToonFunctions:
float ToonShadowMask(float Lambert, float AttenuationSpeed, float ShadowOffset = 0.5)
{
	return smoothstep(ShadowOffset - AttenuationSpeed, ShadowOffset + AttenuationSpeed, Lambert);
}

float CelShadowMask(float Lambert, float AttenuationSpeed)
{
	AttenuationSpeed *= 0.1f;
	return smoothstep(0.5f - AttenuationSpeed, 0.5f + AttenuationSpeed, Lambert);
}

float GetToonSurfaceShadow(float Shadow, float ShadowAttenuationSpeed)
{
	return CelShadowMask(Shadow, ShadowAttenuationSpeed);
}
//皮肤shadow处理
float3 LerpMultiFloat3(float3 Var1, float3 Var2, float3 Var3, float3 Var4, float S)
{
	S *= 3;
	float3 Res;
	Res = lerp(Var1, Var2, saturate(S));
	S--;
	Res = lerp(Res, Var3, saturate(S));
	S--;
	Res = lerp(Res, Var4, saturate(S));
	return Res;
}

float3 GetSkinShadow(float Shadow, float3 Color0)
{
	float3 Color1 = Color0 * float3(0.5,0,0);
	float3 Color2 = Color0 * float3(1.0, 0.5, 0);
	return LerpMultiFloat3(0, Color1, Color2, 1, Shadow);
}

float3 ToonStep(float feather, float halfLambert, float threshold = 0.5f)
{
	return smoothstep(threshold - feather, threshold + feather, halfLambert);
}

half ToonStepHalf(float halfLambert, float smoothness = 0.001f, float threshold = 0.5f)
{
	smoothness = max(smoothness, 0.001f);
	return smoothstep(threshold - smoothness, threshold + smoothness, halfLambert);
}

float ToonFresnel(float3 N, float3 V, float Exponent, float BaseReflectionFraction = 0.0f)
{
	half NoV = max(0.0f, dot(N, V));
	half Fresnel = pow(abs(1 - max(NoV, 0.0f)), Exponent);
	Fresnel = Fresnel * (1 - BaseReflectionFraction) + BaseReflectionFraction;
	return Fresnel;
}

float StrandSpecular(float3 T, float3 L, float3 V, half Exponent, half Scale = 1.0f )
{
	float3 H = normalize(V + L);
	float ToH = dot(T, H);
	float sinTH = sqrt(1.0 - ToH * ToH);

	float dirAttenuation = smoothstep(-1.0, 0.0, ToH);
	return dirAttenuation * pow(sinTH, Exponent) * Scale;
}

float3 ShiftTangent(float3 T, float3 N, half shift)
{
	return normalize(T + shift* N);
}
