#include "../Common.ush"
#include "/Engine/Generated/Material.ush"
#include "/Engine/Generated/VertexFactory.ush"


struct FSimpleMeshPassVSToPS
{
	FVertexFactoryInterpolantsVSToPS FactoryInterpolants;
	float4 Position : SV_POSITION;
};


float3 InputColor;

void MainVS(
	FVertexFactoryInput Input,
	out FSimpleMeshPassVSToPS Output)
{

	float4 ClipSpacePosition;
	
	ResolvedView = ResolveView();

	FVertexFactoryIntermediates VFIntermediates = GetVertexFactoryIntermediates(Input);

	float4 WorldPos = VertexFactoryGetWorldPosition(Input, VFIntermediates);
	float3 WorldNormal = VertexFactoryGetWorldNormal(Input, VFIntermediates);

	float3x3 TangentToLocal = VertexFactoryGetTangentToLocal(Input, VFIntermediates);

	FMaterialVertexParameters VertexParameters = GetMaterialVertexParameters(Input, VFIntermediates, WorldPos.xyz, TangentToLocal);
	WorldPos.xyz += GetMaterialWorldPositionOffset(VertexParameters);

	float4 RasterizedWorldPosition = VertexFactoryGetRasterizedWorldPosition(Input, VFIntermediates, WorldPos);
	ClipSpacePosition = mul(RasterizedWorldPosition, ResolvedView.TranslatedWorldToClip);
	Output.Position = INVARIANT(ClipSpacePosition);
	Output.FactoryInterpolants = VertexFactoryGetInterpolantsVSToPS(Input, VFIntermediates, VertexParameters);
}

void MainPS(
	FSimpleMeshPassVSToPS Input,
	out float4 OutColor1 : SV_Target0,
	out float4 OutColor2 : SV_Target1,
	out float4 OutColor3 : SV_Target2)
{
	// 获取像素的材质参数(此处的材质就是材质辑器编辑出来的材质).
	FMaterialPixelParameters MaterialParameters = GetMaterialPixelParameters(In.FactoryInterpolants, In.SvPosition);
	// FPixelMaterialInputs用于获取材质编辑器的针脚
	// FPixelMaterialInputs PixelMaterialInputs;
	float3 Color1 = float3(0.0, 0.0, 0.0);
	float3 Color2 = float3(0.0, 0.0, 0.0);
	float3 Color3 = float3(0.0, 0.0, 0.0);
#ifdef  HAVE_GetToonMaterialOutput0
	Color1 = LWCToFloat(GetToonMaterialOutput0(MaterialParameters));
#endif
#ifdef  HAVE_GetToonMaterialOutput1
	Color2 = LWCToFloat(GetToonMaterialOutput1(MaterialParameters));
#endif
#ifdef  HAVE_GetToonMaterialOutput2
	Color3 = LWCToFloat(GetToonMaterialOutput2(MaterialParameters));
#endif
	
	//float3 Color = float3(0.0, 0.0, 0.0);
	OutColor1 = float4(Color1, 1.0);
	OutColor2 = float4(Color2, 1.0);
	OutColor3 = float4(Color3, 1.0);
}